CREATE TABLE IF NOT EXISTS restrictions (
    id SERIAL PRIMARY KEY,
    restriction_name VARCHAR DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
